name: dart_ast
description: A new Flutter plugin.
version: 0.0.1
author: huscarter
homepage: huscarter.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  analyzer: ^0.39.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  plugin:
    platforms:
      android:
        package: com.wjs.dart_ast
        pluginClass: DartAstPlugin
      ios:
        pluginClass: DartAstPlugin

