import 'package:dart_ast/ast/ast_node.dart';
import 'package:dart_ast/runtime/runtime_factory.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';

/// The base widget generated by [AstNode].
/// 类名必须是Ast+flutter原生组件名的格式
abstract class AstWidget {
  /// 此tag必须和类名相同，因为在[RuntimeFactory]中有使用
  static final String tag = "AstWidget";

  /// AstNode
  final Expression node;

  AstWidget(this.node);

  /// 用于生成对应的flutter原生组件
  dynamic build();

  /// 生成对应的flutter元素
  // dynamic create(){
  //   return null;
  // }

}
