import 'package:dart_ast/ast/ast_node.dart';
import 'package:flutter/cupertino.dart';

/// The base widget generated by [AstNode].
abstract class AstWidget {

  static final String tag = "AstWidget";

  Widget build(Expression node);

}
