import 'package:dart_ast/ast/ast_node.dart';
import 'package:flutter/cupertino.dart';

/// The base widget generated by [AstNode].
abstract class AstWidget {
  String get name => "AstWidget";

  Widget build(Expression node);
}
